/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.ymsk11.sexp

import com.github.ymsk11.sexp.back.Evaluator
import com.github.ymsk11.sexp.front.Parser

fun main() {
    val parser = Parser()
    val evaluator = Evaluator()

    while (true) {
        val input = readlnOrNull() ?: break
        if (input == ":q") break

        val sexp = parser(input)
        val result = evaluator(sexp)
        println(result)
    }
}
